# action.yml
name: 'AKS Power Switcher'
description: 'Start or stop an AKS cluster.'

inputs:
  action:
    description: 'The action to perform on the cluster. Can be start or stop.'
    required: true
    default: 'start'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.action }}
